# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: order.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'order.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0border.proto\x12\x06orders\"U\n\x05Order\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12 \n\x05items\x18\x03 \x03(\x0b\x32\x11.orders.OrderItem\x12\r\n\x05total\x18\x04 \x01(\x01\"1\n\tOrderItem\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"G\n\x12\x43reateOrderRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12 \n\x05items\x18\x02 \x03(\x0b\x32\x11.orders.OrderItem\"\x1d\n\x0fGetOrderRequest\x12\n\n\x02id\x18\x01 \x01(\t2|\n\x0cOrderService\x12\x38\n\x0b\x43reateOrder\x12\x1a.orders.CreateOrderRequest\x1a\r.orders.Order\x12\x32\n\x08GetOrder\x12\x17.orders.GetOrderRequest\x1a\r.orders.Orderb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDER']._serialized_start=23
  _globals['_ORDER']._serialized_end=108
  _globals['_ORDERITEM']._serialized_start=110
  _globals['_ORDERITEM']._serialized_end=159
  _globals['_CREATEORDERREQUEST']._serialized_start=161
  _globals['_CREATEORDERREQUEST']._serialized_end=232
  _globals['_GETORDERREQUEST']._serialized_start=234
  _globals['_GETORDERREQUEST']._serialized_end=263
  _globals['_ORDERSERVICE']._serialized_start=265
  _globals['_ORDERSERVICE']._serialized_end=389
# @@protoc_insertion_point(module_scope)
