FROM node:16-alpine AS build

WORKDIR /app

COPY ../gateway/package*.json ./

RUN npm install

COPY ../gateway .

#RUN npm run build

FROM node:16-alpine AS production
RUN mkdir -p /protos &&  apk update && apk add --no-cache curl jq
COPY protos /protos
WORKDIR /app

COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app ./
COPY ../gateway/package*.json ./
EXPOSE 3000

CMD ["npx", "ts-node", "./src/server.ts"]
