FROM python:3.9-slim-bullseye AS build

WORKDIR /app

COPY ./users/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY ./users .

FROM python:3.9-slim-bullseye AS production

WORKDIR /app

COPY --from=build /usr/local/lib/python3.9/site-packages /usr/local/lib/python3.9/site-packages
COPY --from=build /app /app

EXPOSE 50051

CMD ["python", "server.py"]
